### ISSUE TITLE
Is there any consideration on the start order for db server and archive server ?

### ISSUE THREAD

**Issue by OrNot** [dcm4che-dockerfiles/dcm4chee-arc-psql#1]
With docker-compose, even "links" is given , there seems still  no guarantee for the db server surely to start before the archive server is started.  will it be an issue ?

**Comment by gunterze** [comment]
I only got the error on first start up, when LDAP and DB have to be intialized. I will take a closer look into it when evaluating usage of docker swarm for support to distribute services over several nodes.

**Comment by OrNot** [comment]
Here is an article on controlling the start order with docker-compose, which may be worth reading in case you have not .  https://docs.docker.com/compose/startup-order/
 

    On Monday, April 4, 2016 11:35 PM, Gunter Zeilinger <notifications@github.com> wrote:
 

 I only got the error on first start up, when LDAP and DB have to be intialized. I will take a closer look into it when evaluating usage of docker swarm for support to distribute services over several nodes.—

**Comment by gunterze** [comment]
base image dcm4che/wildfly:10.0.0.Final supports now to specify a space separated list of host:port entries by ENV WILDFLY_WAIT_FOR, which are check for listening, before Wildfly is started. So you may set
```yaml
  environment:
    WILDFLY_WAIT_FOR: ldap:389 db:5432
```
to ensure that the archive get not started before slapd and PostgreSQL become listening.
