### ISSUE TITLE
Define AWS S3 as storage descriptor 

### ISSUE THREAD

**Issue by carlespibernat** [dcm4che-dockerfiles/dcm4chee-arc-psql#10]
Hi!

I'm trying to deploy a dcm4chee with docker in an amazon ECS cluster and I want to configure AWS S3 to store my DICOM images. 
I've managed to deploy it and to configure the storage descriptor through dcm4chee ui but I'm afraid that if ECS for any reason (autoscaling, maintenance...) redeploys the app the I'll loose my configuration.

How can I configure it through Docker environment variables? 

Thanks!!

**Comment by gunterze** [comment]
You have to take care that the LDAP data files accessed by the LDAP container survive ECS service transactions..
