### ISSUE TITLE
Problem installing using the readme guide

### ISSUE THREAD

**Issue by mkauzlar** [dcm4che-dockerfiles/dcm4chee-arc-psql#3]
Using the provided docker-compose.env  and docker-compose.yml i get:

Pulling dcm4chee-arc (dcm4che/dcm4chee-arc-psql:5.9.3-logstash-secure-ui)...
Pulling repository docker.io/dcm4che/dcm4chee-arc-psql
ERROR: Tag 5.9.3-logstash-secure-ui not found in repository docker.io/dcm4che/dcm4chee-arc-psql

**Comment by gunterze** [comment]
the last offical released docker version is 5.9.2. The docker-compose.yml
in github already reflects the next version, and test builds of the next
version by docker hub syncs the repository description with the README.md
at github.

**Comment by gunterze** [comment]
I will no longer trigger pre-builds of the next version by docker hub, but upload them manually, to avoid updating the description for the repository at dockerhub before release.
