### ISSUE TITLE
links in read.me files not working

### ISSUE THREAD

**Issue by marcheschi** [dcm4che-dockerfiles/dcm4chee-arc-psql#8]
Hi these links are not working anymore:
5.14.0 (5.14.0/Dockerfile)
5.14.0-secure (5.14.0-secure/Dockerfile)
5.14.0-secure-ui (5.14.0-secure-ui/Dockerfile)
5.14.0-logstash (5.14.0-logstash/Dockerfile)
5.14.0-logstash-secure (5.14.0-logstash-secure/Dockerfile)
5.14.0-logstash-secure-ui (5.14.0-logstash-secure-ui/Dockerfile)

Can you correct them ?
Thank you
Paolo

**Comment by gunterze** [comment]
Links will work after tag of 5.14.0 release
